## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Deliverable_Data/WeatherPy_database.csv")
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Rikitea,PF,-23.1203,-134.9692,78.22,71,87,9.57,light rain
1,1,Lensk,RU,60.7253,114.9278,8.58,93,99,5.99,overcast clouds
2,2,Rosetta,EG,31.4044,30.4164,57.02,63,79,25.34,broken clouds
3,3,Jamestown,US,42.0970,-79.2353,21.09,62,100,5.01,mist
4,4,Vallenar,CL,-28.5708,-70.7581,84.92,18,0,10.22,clear sky
5,5,Vaini,TO,-21.2000,-175.2000,79.68,84,100,20.71,light rain
6,6,Faanui,PF,-16.4833,-151.7500,80.44,73,19,14.70,few clouds
7,7,Brae,GB,60.3964,-1.3530,37.31,62,100,34.45,overcast clouds
8,8,Urumqi,CN,43.8010,87.6005,-1.25,85,75,2.24,fog
9,9,Hilo,US,19.7297,-155.0900,68.11,74,40,9.22,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

In [5]:
# 4a. Determine if there are any empty rows.

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    

    # 6e. Make request and retrieve the JSON data from the search. 
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.

In [9]:
# 7. Drop the rows where there is no Hotel Name.

In [10]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure